export default {
  data: {
    memes: [
      {
        id: 0,
        name: "meme-0",
        url: "src/assets/meme-0.png",
        width: 1200,
        height: 1200,
        box_count: 2,
      },
      {
        id: 1,
        name: "meme-1",
        url: "src/assets/meme-1.avif",
        width: 1200,
        height: 1200,
        box_count: 2,
      },
      {
        id: 2,
        name: "meme-2",
        url: "src/assets/meme-2.avif",
        width: 1200,
        height: 1200,
        box_count: 3,
      },
      {
        id: 3,
        name: "meme-3",
        url: "src/assets/meme-3.avif",
        width: 1200,
        height: 1200,
        box_count: 4,
      },
      {
        id: 4,
        name: "meme-4",
        url: "src/assets/meme-4.avif",
        width: 1200,
        height: 1200,
        box_count: 5,
      },
      {
        id: 5,
        name: "meme-5",
        url: "src/assets/meme-5.avif",
        width: 1200,
        height: 1200,
        box_count: 6,
      },
      {
        id: 6,
        name: "meme-6",
        url: "src/assets/meme-6.avif",
        width: 1200,
        height: 1200,
        box_count: 7,
      },
      {
        id: 7,
        name: "meme-7",
        url: "src/assets/meme-7.avif",
        width: 1200,
        height: 1200,
        box_count: 8,
      },
    ],
  },
};
